# Permalinks
permalink:           pretty

# Setup
title:               Jack Olmstead
tagline:             Data Science For The Common Man
url:                 http://JOlmstead495.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jack Olmstead
  email:             J.M.Olmstead10@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/JOlmstead495

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
